accounts:
  - name: alice
    coins: ["2000000mdc"]
  - name: bob
    coins: ["10000mdc"]
validator:
  name: alice
  staked: "1000000mdc"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["5mdc"]
genesis:
  app_state:
    staking:
      params:
        bond_denom: "mdc"